#if !canImport(ObjectiveC)
    import XCTest

    extension LogDogCryptoSwiftTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__LogDogCryptoSwiftTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(LogDogCryptoSwiftTests.__allTests__LogDogCryptoSwiftTests),
        ]
    }
#endif
